// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Blog
{
    public int BlogId { get; set; }

    public int AuthorId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string ImageUrl { get; set; }

    public int Views { get; set; }

    public int Likes { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User Author { get; set; }
}