// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Child
{
    public int ChildId { get; set; }

    public int UserId { get; set; }

    public string FullName { get; set; }

    public string ParentName { get; set; }

    public string ParentNumber { get; set; }

    public DateTime BirthDate { get; set; }

    public string Gender { get; set; }

    public string BloodType { get; set; }

    public string AllergiesNotes { get; set; }

    public bool Status { get; set; }

    public string MedicalHistory { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdateAt { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<ConsultationRequest> ConsultationRequests { get; set; } = new List<ConsultationRequest>();

    public virtual ICollection<DailyRecord> DailyRecords { get; set; } = new List<DailyRecord>();

    public virtual ICollection<GrowthRecord> GrowthRecords { get; set; } = new List<GrowthRecord>();

    public virtual User User { get; set; }
}