// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class ConsultationResponse
{
    public int ResponseId { get; set; }

    public int RequestId { get; set; }

    public int DoctorId { get; set; }

    public string Response { get; set; }

    public string Attachments { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User Doctor { get; set; }

    public virtual ConsultationRequest Request { get; set; }
}