// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class DailyRecord
{
    public int RecordId { get; set; }

    public int ChildId { get; set; }

    public DateOnly RecordDate { get; set; }

    public int MilkAmount { get; set; }

    public int FeedingTimes { get; set; }

    public int DiaperChanges { get; set; }

    public decimal SleepHours { get; set; }

    public string Note { get; set; }

    public virtual Child Child { get; set; }
}