// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class DoctorProfile
{
    public int DoctorProfileId { get; set; }

    public int UserId { get; set; }

    public string Specialization { get; set; }

    public string Qualification { get; set; }

    public int Experience { get; set; }

    public string LicenseNumber { get; set; }

    public string Biography { get; set; }

    public decimal AverageRating { get; set; }

    public int TotalRatings { get; set; }

    public bool IsVerified { get; set; }

    public virtual User User { get; set; }
}