// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class GrowthRecord
{
    public int RecordId { get; set; }

    public int ChildId { get; set; }

    public decimal Height { get; set; }

    public decimal Weight { get; set; }

    public decimal Bmi { get; set; }

    public decimal HeadCircumference { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Child Child { get; set; }
}